- op: add
  path: /spec/template/spec/runtimeClassName
  value: runsc
target:
  kind: Deployment
  name: orchestra-agent
- op: replace
  path: /spec/minReplicaCount
  value: 1
target:
  kind: ScaledObject
  name: orchestra-agent-scaler
